### ISSUE TITLE
Picke file load issue

### ISSUE THREAD

**Issue by Abdulk084** [ncats/herg-ml#2]
I am getting `UnpicklingError: invalid load key, 'v'.` error while loading the pickle file in jupyter notebook. Do you think pickle file might be corrupted.

**Comment by iwwwish** [comment]
I am guessing the pickle file might not have been downloaded properly. Did you use git-lfs (see [README](https://github.com/ncats/herg-ml/blob/master/README.md) for instructions) to fetch the large files? Some of the pickle files are large.

Best,
Vishal
